### ISSUE TITLE
utf-8 decoding error 

### ISSUE THREAD

**Issue by thezenox** [microsoft/serial-monitor-cli#6]
Problem: 
`'utf-8' codec can't decode byte 0xff in position 6: invalid start byte`

Can be fixed by adding 'ignore' in `print_to_console_json`
`data = data.decode('utf-8', 'ignore').strip()`

**Comment by gcampbell-msft** [comment]
Hi @thezenox, we've fixed this issue in the latest release. However, we used 'replace' instead of 'ignore', but it should stop any crashes in the serial-monitor-cli due to decoding problems
